ipfs/js-ipfs-repo

README.md, package.json, src/index.js, src/stores/index.js, src/stores/locks.js, src/stores/version.js, tests/repo-test.js
-> https://github.com/ipfs/js-ipfs-repo/issues/9
=> WIP - locks

package.json, src/stores/config.js, src/stores/datastore.js, tests/browser-tests.js
=> Get tests to pass using indexeddb instead of local-storage

package.json, tests/browser-tests.js, tests/repo-test.js
Makes file buffers have the same content and length on both node and browser. 
Related to https://github.com/ipfs/js-ipfs/pull/62 and https://github.com/ipfs/js-ipfs/pull/61
=> Use buffer-loader on tests instead of raw-loader

src/index.js, src/stores/version.js, tests/node-tests.js
Calling repo.exists() on a repo that doesn't exist would return an error
rather than false, which would also mask whatever the underlying error
really was.
=> No longer considers a non-existant repo an error.

README.md, package.json, src/index.js, test/repo-test.js
The README example could still use work (e.g. demonstrate how we might use it in js-ipfs proper).
=> Code cleanup, better coverage, readme improvements

src/stores/datastore.js, test/repo-test.js
found that extensions were defaulting to 'data', while running block-service tests. This PR fixes it
=> fix extension

package.json, src/stores/blockstore.js, src/stores/locks.js, test/blockstore-test.js
=> Awesome IPLD Endeavour

package.json, src/default-options-browser.js, src/default-options.js, src/index.js, test/browser.js, test/node.js, test/options-test.js, test/repo-test.js
There were some issues introduced with #136. This should be reverted for now, until it is cleared to not cause any issues.
=> fix: add backwards compatibility and more tests

src/index.js
Expose the repo version for access even when a repo hasn't been initialized.
discussion: [js-ipfs#1181](https://github.com/ipfs/js-ipfs/pull/1181/files#r163727102)
ref: [js-ipfs#1188](https://github.com/ipfs/js-ipfs/pull/1188)
=> Expose the current repo version

README.md, package.json, src/blockstore.js, src/index.js, test/node.js, test/stat-test.js
To implement this, I take a look at [Go's repo.stat implementation](https://github.com/ipfs/go-ipfs/blob/4c392928b48db4cdd8853234202ab97c78e3d56b/core/corerepo/stat.go) and I basically do the same on each one except on `repoSize`.
- For `numObjects` I use the number of blocks on the Blockstore
- For `repoPath` I just used `this.path`
- For `version` I use `this.version.get`
- For `storageMax` I use the config `Datastore.StorageMax` or the maximum integer number.
- For `repoSize` I sum the number of bytes of the blocks and their keys from the Blockstore + the same for the Datastore and the Keystore. This doesn't count with `api` and ´config` files' size but it won't differ much from the real size. 
I also added a simple test.
=> Implement .stat() function

README.md, src/index.js, test/lock-test.js, test/node.js, test/options-test.js
* Allows users to create custom repo locks, such as to support the new s3 datastore
* ~~Allows users to have no repo locking~~
resolves ipfs/js-ipfs-repo#161
=> feat(lock): allow for custom lock options

src/index.js
Allow for `require('ipfs-repo').errors` instead of `require('ipfs-repo/src/errors')`
=> fix: expose errors to resolve need for antipattern require

src/config.js, test/node.js
In order to comply with this new standard rule ☺️ 
https://github.com/standard/eslint-config-standard/pull/133
=> Prefer const over let

package.json, src/index.js, src/lock.js, test/lock-test.js, test/node.js
This PR swaps lock-me for proper-lockfile which fixes compat with node 11 and also brings others improvements https://github.com/moxystudio/node-proper-lockfile.
- better support for network file systems 
- staleness support
- better clean up for process shutdown
ref: https://github.com/ipfs/js-ipfs/issues/1700
=> fix: fix lock for node 11

src/lock.js
This PR fixes this https://github.com/ipfs/js-ipfs-repo/pull/181#issuecomment-440218312 
For context the problem isn't about that stack trace, the problem is about the staleness checks https://github.com/moxystudio/node-proper-lockfile#design. 
The lockfile mtime is updated periodically (5s) to prevent staleness, and there's a threshold of up to 10s to mark a lock as stale. 
What happens is that ipfs some how locks the event loop for so long that `proper-lockfile` marks the lock as compromised because it takes more than 5s to update mtime again and so we hit the limit of 10s. Hope this makes sense lol :)
This fix just increases the stale threshold to 20s and that should be enough, but its a naive fix and if we need to further increase this threshold we should really dig into it more. 
To …
=> fix: fix staleness check

example.js, package.json, src/blockstore.js, src/index.js, src/lock.js, test/blockstore-test.js, test/repo-test.js, test/stat-test.js
This changes the blockstore to check for a CID of the other version (if applicable) when getting data or checking for existence.
If content is found for the other version of a CID then we `put` that block in the store under the passed CID. This causes some duplication.
When we migrate to using multihash as key instead of CID these duplicates will be purged.
FYI this is the same strategy that go-ipfs uses currently: https://github.com/ipfs/go-ipfs/pull/5285
~~depends on https://github.com/multiformats/js-cid/pull/71~~
Allows us to pass [these interop tests](https://github.com/ipfs/interop/pull/46):
=> feat: cid agnostic blockstore .get and .has

src/lock.js
This PR makes the repo lock safer with callback/promise conversion, using then second arg we don't catch error inside the first arg fn and avoid callback already called errors.
Plus changes 2 two test to use the new buffer api.
=> fix: fix repo lock and buffer api

package.json, src/index.js
A subset of https://github.com/ipfs/js-ipfs-repo/pull/186 - unfortunately this change was released as a patch version in other modules so I'm expediting it here so that js-ipfs can consistently return a bignumber.js not a big.js for both `stats.repo` and `stats.bw`.
bignumber.js is a drop in replacement for big.js with more functionality so you could consider this change a minor.
=> refactor: switch to bignumber.js

package.json, test/lock-test.js
So we can get the benefits of https://github.com/ipfs/js-datastore-level/pull/15
=> chore: update datastore-level

src/errors/index.js, src/lock-memory.js, test/browser.js, test/lock-test.js
Memlock throws error when lock exists
Fix for memlock to throw an error when trying to acquire already
existing lock.
License: MIT
Signed-off-by: Adam Uhlir <uhlir.a@gmail.com>
=> Memlock throws error when lock exists

README.md, src/blockstore-utils.js, src/blockstore.js, src/index.js, test/blockstore-utils-test.js, test/browser.js, test/node.js
These have already been duplicated twice in js-ipfs. This exposes utility functions to encode a CID as a blockstore Key and decode a blockstore Key to a CID.
refs https://github.com/ipfs/js-ipfs/pull/2022/files#r303389863
=> feat: export blockstore key encode/decode utils

test/stat-test.js
Prior to this change running only the stat tests via:
npx mocha test/node.js --grep stats
would fail, as they expect to have data in the repo.
=> test: make stat test independent of other tests

.travis.yml, README.md, src/blockstore.js
Allows streaming into the blockstore. The blockstore currently uses the batch functionality of the underlying datatore, so we might need to change `interface-datastore` next to add streaming primitives but this at least allows streaming this far down the stack.
BREAKING CHANGE: you must pass an iterable or async iterable to putMany - this should be relatively painless as the current API is to pass an array which is iterable, but it does change the API and rules is rules.
=> feat: accept async iterators into blockstore.putMany

package.json, src/config.js
This bumps `p-queue` to ^6.0.0 to resolve `p-queue` version mismatch issues with `mortice` when using `ipfs` in Electron. 
https://github.com/ipfs/js-ipfs/issues/2374
=> Bumped p-queue to ^6.0.0

src/index.js, test/repo-test.js
blocks, keys and datastore are being closed in repo.close() but root is not.
=> fix: close root datastore

README.md, package.json, src/index.js, test/stat-test.js
`stat()` method was accepting an object called `options`. The only option available was `human` that was changing the stats' output to be human-readable. 
`human` option was just a formatting functionality and it should be kept out of `ipfs-core`. See https://github.com/ipfs/js-ipfs-repo/pull/213#issuecomment-555488344 for further details.
Thus, this PR removes the `options` object.
=> feat: remove options object from stat method

package.json, src/default-options-browser.js, test/options-test.js
Between `level-js@2` and `level-js@4` it started passing version numbers into  `indexedDB.open` so we have to specify these now.  It also prefixes locations with a disambiguator, which we need to set to blank for browsers to still be able to read their previously created databases.
Depends on:
- ~[ ] https://github.com/ipfs/js-ipfs-repo/pull/217~
=> fix: pass backwards-compatible level-js options

README.md, src/index.js, test/browser.js, test/is-initialized.js, test/node.js
A few places need ot know whether or not a repo has been initialised and do so by a variety of methods - checking whether certain files exist, etc.
This PR adds an `isInitialized()` method to the ipfs repo class to take some of this guesswork away as the repo will know if it's been initialised.
=> feat: add isInitialized method

README.md, package.json, src/config.js, test/api-addr-test.js, test/blockstore-test.js, test/blockstore-utils-test.js, test/config-test.js, test/datastore-test.js, test/interop-test.js, test/is-initialized.js, test/keystore-test.js, test/lock-test.js, test/migrations-test.js, test/options-test.js, test/repo-test.js, test/stat-test.js, test/utils/chai.js
The config .get/.set methods are overloaded to allow the user to retrieve or replace the entire config.  This is an error prone approach that could end with the user invalidating their config when they did not mean to.
The change here adds `.replace` and `.getAll` methods to allow the user to be specific about their intentions and hopefully makes the API slightly less of a foot-gun.
=> feat: adds .replace and .getAll methods to config

README.md, src/blockstore-utils.js, src/blockstore.js, test/blockstore-test.js
Similar to `repo.blocks.putMany` this adds a `repo.blocks.deleteMany` method that allows for deleting lots of blocks in one go.
=> feat: add deleteMany method

README.md
We switched from datastore-level-js to datastore-idb in `2.0.0` so update the diagram to reflect that.
=> docs: update architecture diagram in readme

package.json, src/default-options-browser.js
`level-js` seems to handle datastore mutations during queries better which we need for datastore migrations.
Revisit once https://github.com/ipfs/js-datastore-idb/issues/6 is resolved.
=> feat: use datastore-level in the browser again

package.json, test/api-addr-test.js, test/blockstore-test.js, test/blockstore-utils-test.js, test/config-test.js, test/datastore-test.js, test/interop-test.js, test/is-initialized.js, test/keystore-test.js, test/lock-test.js, test/migrations-test.js, test/node.js, test/options-test.js, test/pins-test.js, test/repo-test.js, test/stat-test.js, test/utils/chai.js
chai is bundled & configured by aegir so we don't need to depend on
it separately.
=> chore: remove redundant chai deps

package.json, src/api-addr.js, src/config.js, src/index.js, src/lock-memory.js, src/lock.js, src/spec.js, src/version.js
BREAKING CHANGE: updates ipld-block to 0.11.0 which is not compatible with earlier versions (fails `expect(v11Block).to.deep.equal(v10Block)` for example)
=> chore: update deps

src/types.d.ts
These were missing from the types
=> chore: add config keys for Announce and NoAnnounce addresses

package.json, src/blockstore.js, src/types.d.ts, test/blockstore-test.js
It should not leak datastore keys, instead return the cids you deleted.
Lets us not depend on ipfs-repo or interface-datastore in the types of
ipfs-blockstore, then ipld, then ipfs-http-client.
=> fix: return type of deleteMany should be the cids you deleted

package.json, src/pins.js, src/utils/walk-dag.js, test/blockstore-test.js
Use the `.links()` function from the multiformats block class, no need to reinvent the wheel.
=> fix: walk dag for all supported codecs

packages/ipfs-repo/src/idstore.js
Fixes webpack error:
```
Module not found: Error: Can't resolve 'process/browser' in /path/...
```
Falls back to `setImmediate`, then `setTimeout`.
=> fix: access process from globalThis

packages/ipfs-repo-migrations/src/index.js, packages/ipfs-repo/package.json, packages/ipfs-repo/src/pin-manager.js, packages/ipfs-repo/test/pins-test.js
Storing a set of seen CIDs to short-cut DAG traversal while ensuring we have all the blocks in a DAG in the blockstore can cause OOMs for very large DAGs so replace the unbounded `Set` with a `LRU` cache with a configurable maximum size.
=> fix: OOM on large DAGs
